source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Ora_Example', :exclusive => true do
  pod 'Ora', :path => '../'
end

target 'Ora_Tests', :exclusive => true do
  pod 'Ora', :path => '../'

  
end
